### ISSUE TITLE
Alternative to Bloc suggestion

### ISSUE THREAD

**Issue by frank06** [felipebueno/stacker_news#1]
Yes! Nice work!

This is not an issue. You mentioned wanted to look for something simpler than BLoC, may I suggest Riverpod? I've had tremendous success with it in a decently sized app.

Btw, if you like that approach (and can tolerate Hive for now) check out https://github.com/flutterdata/flutter_data – I'm the author, shameless plug!  Again if you like notifiers better than streams, it's insanely productive and quite mature by now. Reactive relationships is what I like the most. Feel free to ask me any questions, or completely ignore this message. All the best.

**Comment by felipebueno** [comment]
Hey @frank06 !

I appreciate the suggestions, man!

> https://github.com/flutterdata/flutter_data

I'll take a look at flutter_data later as I can definitely tolerate Hive :slightly_smiling_face: In fact, I've been a happy Hive user for at least four year now.  I was really bummed when they announced the deprecation in favor of Isar. Today I'm still using Hive because it's too hard to migrate my (huge) apps to Isar and, to be frank (no pun intended), I don't think I'll ever use it.

> may I suggest Riverpod? I've had tremendous success with it in a decently sized app

Yes, I am considering Riverpod.

I'll keep this issue open for when I start to replace BLoC. Feel free to post any other suggestion here :+1:

**Comment by frank06** [comment]
All good! Well, I've used both and we're currently migrating lots of users to Isar in production. Isar's queries are pretty cool. If anything feel free to ping me

**Comment by felipebueno** [comment]
Hi, @frank06

I (finally) removed the BLoC stuff. I did not commit with any other state management strategy yet. For now I'm just using good old FutureBuilders and Statefull Widgets (when necessary).

https://github.com/felipebueno/stacker_news/commit/181c9797ba15471b4bdbe8119011c5f649c1a1ec

**Comment by felipebueno** [comment]
I'm going to close this issue for now. Maybe I'll revisit it when things get too messy to handle and a more robust state management strategy is needed.

Thanks, @frank06!
